"""Keyword tuples shared across classification, scope, and rules fallback."""

SUPPORT_QUESTION_HINTS = (
    "buyurtma",
    "tovar",
    "yetkaz",
    "to'lov",
    "qancha",
    "qayerda",
    "qaytar",
    "original",
    "sifat",
    "ilova",
    "punkt",
    "kompaniya",
    "sahiy",
    "kafolat",
    "zakaz",
    "malumot",
    "qachon",
)

OPERATOR_REQUEST_PHRASES = (
    "operator kerak",
    "operatorga",
    "operatorga ul",
    "jonli operator",
    "odam bilan",
    "mutaxassis bilan",
    "operator chaqir",
    "operator bog",
)

OFF_TOPIC_KEYWORDS = (
    "futbol",
    "football",
    "barsa",
    "barcelona",
    "real madrid",
    "madrid",
    "chelsea",
    "manchester",
    "liverpool",
    "messi",
    "ronaldo",
    "nechchi",
    "hisob",
    "o'yin natija",
    "chempion",
    "liga",
    "ob-havo",
    "obhavo",
    "kino",
    "film",
    "serial",
    "musiqa",
    "qo'shiq",
    "siyosat",
    "prezident",
    "matematika",
    "fizika",
    "dasturlash",
    "python dars",
    "vikipediya",
    "google qidir",
    "sevgilim",
    "qizi bormi",
    "yaxshi ko'rgan",
    "tanishmoq",
    "uylanganmisiz",
    "shaxsiy hayot",
    "instagram",
    "tiktok",
    "mem",
    "hazil",
)
